### ISSUE TITLE
validation.uploaded Error

### ISSUE THREAD

**Issue by antwonw** [LinkStackOrg/winter-wonderland#4]
I get a `validation.uploaded` error when attempting to upload this theme, `v1.6`.

<img width="400" alt="Screen Shot 2023-08-10 at 2 10 10 PM" src="https://github.com/LinkStackOrg/Cloudy-Storm/assets/519934/a29a8d3a-6f01-41ed-973a-46f1f915539c">

**Comment by lastsamurai26** [comment]
Unfortunately, I cannot reproduce this problem. Can you please tell me?
what version of Linkstack you are using.
I just uploaded version 1.6 Winter Wonderland in my test environment and I can use it without any problems.

**Comment by craeckor** [comment]
It's a server-side issue but has nothing to do with LinkStack directly. It's a php default limitation. The problem is upload_max_filesize which is set to 2MB and post_max_size which is set to 8MB (this isn't really a problem because Winter-Wonderland is only ~3MB) as default (at least for me (i use Openlitespeed)). You can test it with a high-resolution picture like [this](https://wall.alphacoders.com/big.php?i=982215) one. You will get the same Error.
For Apache add the following two lines to .htaccess which should be in your WEBROOT:
```
php_value upload_max_filesize 20M
php_value post_max_size 21M
```
Save the file and restart Apache.

For Openlitespeed go to Virtual Hosts --> View LinkStack --> General --> php.ini Override --> Edit --> Paste the same two lines as mentioned above and save it --> Graceful Restart

For NGINX open the php.ini File with ```sudo nano /etc/php8*/fpm/php.ini``` and paste the same two lines as mentioned above and save it + Open your NGINX Config and add ```client_max_body_size 21m;``` to your ```server { ... }``` block. This will gonna look something like the following:
```
server {

    ...

   client_max_body_size 21m;

   ...

}
```

**Comment by forgeOneHQ** [comment]
I think that issue can be closed since it is a server side configuration issue and I was able to upload all latest themes without problem to the self-hosted instance.
